export const POPULAR_SERVICES = [
  {
    id: "netflix",
    name: "Netflix",
    category: "entertainment",
    defaultPrice: 15.49,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Credit Card",
    color: "#E50914",
    bgColor: "bg-red-950/40 border-red-500/30 text-red-400",
    badgeColor: "bg-red-500/20 text-red-400 border-red-500/30",
    icon: "netflix",
  },
  {
    id: "youtube",
    name: "YouTube Premium",
    category: "entertainment",
    defaultPrice: 13.99,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Google Pay",
    color: "#FF0000",
    bgColor: "bg-red-950/30 border-red-500/20 text-red-500",
    badgeColor: "bg-red-500/20 text-red-400 border-red-500/30",
    icon: "youtube",
  },
  {
    id: "spotify",
    name: "Spotify",
    category: "entertainment",
    defaultPrice: 11.99,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "PayPal",
    color: "#1DB954",
    bgColor: "bg-emerald-950/40 border-emerald-500/30 text-emerald-400",
    badgeColor: "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
    icon: "spotify",
  },
  {
    id: "disney",
    name: "Disney+",
    category: "entertainment",
    defaultPrice: 13.99,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Credit Card",
    color: "#113CCF",
    bgColor: "bg-blue-950/40 border-blue-500/30 text-blue-400",
    badgeColor: "bg-blue-500/20 text-blue-400 border-blue-500/30",
    icon: "disney",
  },
  {
    id: "apple",
    name: "Apple One / TV+",
    category: "entertainment",
    defaultPrice: 9.99,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Apple Pay",
    color: "#A2AAAD",
    bgColor: "bg-slate-900 border-slate-700 text-slate-200",
    badgeColor: "bg-slate-800 text-slate-300 border-slate-700",
    icon: "apple",
  },
  {
    id: "amazon",
    name: "Amazon Prime",
    category: "entertainment",
    defaultPrice: 14.99,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Amazon Pay",
    color: "#00A8E1",
    bgColor: "bg-cyan-950/40 border-cyan-500/30 text-cyan-400",
    badgeColor: "bg-cyan-500/20 text-cyan-400 border-cyan-500/30",
    icon: "amazon",
  },
  {
    id: "chatgpt",
    name: "ChatGPT Plus",
    category: "productivity",
    defaultPrice: 20.00,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Credit Card",
    color: "#10A37F",
    bgColor: "bg-teal-950/40 border-teal-500/30 text-teal-300",
    badgeColor: "bg-teal-500/20 text-teal-300 border-teal-500/30",
    icon: "chatgpt",
  },
  {
    id: "github",
    name: "GitHub Copilot",
    category: "productivity",
    defaultPrice: 10.00,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Credit Card",
    color: "#FFFFFF",
    bgColor: "bg-zinc-900 border-zinc-700 text-zinc-100",
    badgeColor: "bg-zinc-800 text-zinc-300 border-zinc-700",
    icon: "github",
  },
  {
    id: "google",
    name: "Google One",
    category: "productivity",
    defaultPrice: 2.99,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Google Pay",
    color: "#4285F4",
    bgColor: "bg-blue-950/40 border-blue-500/30 text-blue-400",
    badgeColor: "bg-blue-500/20 text-blue-400 border-blue-500/30",
    icon: "google",
  },
  {
    id: "notion",
    name: "Notion Plus",
    category: "productivity",
    defaultPrice: 10.00,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Credit Card",
    color: "#FFFFFF",
    bgColor: "bg-stone-900 border-stone-700 text-stone-200",
    badgeColor: "bg-stone-800 text-stone-300 border-stone-700",
    icon: "notion",
  },
  {
    id: "figma",
    name: "Figma Professional",
    category: "productivity",
    defaultPrice: 15.00,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Credit Card",
    color: "#F24E1E",
    bgColor: "bg-purple-950/40 border-purple-500/30 text-purple-400",
    badgeColor: "bg-purple-500/20 text-purple-400 border-purple-500/30",
    icon: "figma",
  },
  {
    id: "adobe",
    name: "Adobe Creative Cloud",
    category: "productivity",
    defaultPrice: 59.99,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Credit Card",
    color: "#FF0000",
    bgColor: "bg-red-950/40 border-red-500/30 text-red-400",
    badgeColor: "bg-red-500/20 text-red-400 border-red-500/30",
    icon: "adobe",
  },
  {
    id: "discord",
    name: "Discord Nitro",
    category: "entertainment",
    defaultPrice: 9.99,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "PayPal",
    color: "#5865F2",
    bgColor: "bg-indigo-950/40 border-indigo-500/30 text-indigo-400",
    badgeColor: "bg-indigo-500/20 text-indigo-400 border-indigo-500/30",
    icon: "discord",
  },
  {
    id: "playstation",
    name: "PlayStation Plus",
    category: "entertainment",
    defaultPrice: 79.99,
    currency: "USD",
    frequency: "yearly",
    paymentMethod: "PlayStation Store",
    color: "#003791",
    bgColor: "bg-blue-950/40 border-blue-500/30 text-blue-300",
    badgeColor: "bg-blue-500/20 text-blue-300 border-blue-500/30",
    icon: "playstation",
  },
  {
    id: "xbox",
    name: "Xbox Game Pass",
    category: "entertainment",
    defaultPrice: 16.99,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Microsoft Pay",
    color: "#107C10",
    bgColor: "bg-emerald-950/40 border-emerald-500/30 text-emerald-400",
    badgeColor: "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
    icon: "xbox",
  },
  {
    id: "duolingo",
    name: "Duolingo Super",
    category: "education",
    defaultPrice: 6.99,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "App Store",
    color: "#58CC02",
    bgColor: "bg-lime-950/40 border-lime-500/30 text-lime-400",
    badgeColor: "bg-lime-500/20 text-lime-400 border-lime-500/30",
    icon: "duolingo",
  },
  {
    id: "coursera",
    name: "Coursera Plus",
    category: "education",
    defaultPrice: 59.00,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Credit Card",
    color: "#0056D2",
    bgColor: "bg-sky-950/40 border-sky-500/30 text-sky-400",
    badgeColor: "bg-sky-500/20 text-sky-400 border-sky-500/30",
    icon: "coursera",
  },
  {
    id: "strava",
    name: "Strava Summit",
    category: "health",
    defaultPrice: 11.99,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Credit Card",
    color: "#FC4C02",
    bgColor: "bg-orange-950/40 border-orange-500/30 text-orange-400",
    badgeColor: "bg-orange-500/20 text-orange-400 border-orange-500/30",
    icon: "strava",
  },
  {
    id: "headspace",
    name: "Headspace",
    category: "health",
    defaultPrice: 12.99,
    currency: "USD",
    frequency: "monthly",
    paymentMethod: "Credit Card",
    color: "#F47D31",
    bgColor: "bg-amber-950/40 border-amber-500/30 text-amber-400",
    badgeColor: "bg-amber-500/20 text-amber-400 border-amber-500/30",
    icon: "headspace",
  }
];

export const CATEGORIES = [
  { id: "entertainment", label: "Entertainment", color: "text-purple-400 border-purple-500/30 bg-purple-500/10" },
  { id: "productivity", label: "Productivity", color: "text-blue-400 border-blue-500/30 bg-blue-500/10" },
  { id: "education", label: "Education", color: "text-emerald-400 border-emerald-500/30 bg-emerald-500/10" },
  { id: "health", label: "Health & Fitness", color: "text-rose-400 border-rose-500/30 bg-rose-500/10" },
  { id: "other", label: "Other", color: "text-slate-400 border-slate-500/30 bg-slate-500/10" }
];

export const CURRENCIES = ["USD", "EUR", "GBP", "JPY", "AUD"];
export const FREQUENCIES = [
  { id: "daily", label: "Daily" },
  { id: "weekly", label: "Weekly" },
  { id: "monthly", label: "Monthly" },
  { id: "yearly", label: "Yearly" }
];
